default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: rails-tutorial-db

development:
  <<: *default
  database: rails_tutorial_app_development

test:
  <<: *default
  database: rails_tutorial_app_test

production:
  <<: *default
  database: rails_tutorial_app_production